name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]

    steps:
      -   name: Checkout
          uses: actions/checkout@v3

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: "none"
            php-version: ${{ matrix.php }}

      -   name: Docker compose up
          run: docker compose up -d

      -   name: Install dependencies
          run: composer install --no-interaction --no-progress --no-suggest

      -   name: Run tests
          run: vendor/bin/pest

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v3

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: "none"
            php-version: "8.4"

      -   name: Install dependencies
          run: composer install --no-interaction --no-progress --no-suggest

      -   name: Run phpstan
          run: vendor/bin/phpstan analyse --ansi --no-progress